package com.pms.pharmacy.entity;

public enum DrugCategory {
    ANTIBIOTIC,
    ANALGESIC,
    ANTIHYPERTENSIVE,
    ANTIDIABETIC,
    ANTIHISTAMINE,
    ANTIFUNGAL,
    ANTIVIRAL,
    CARDIOVASCULAR,
    NEUROLOGICAL,
    GASTROINTESTINAL,
    RESPIRATORY,
    DERMATOLOGICAL,
    VITAMIN_SUPPLEMENT,
    HORMONAL,
    ONCOLOGY,
    OTHER
}
